# Generated by Django 5.0.1 on 2026-02-19 09:49

import core.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('target_audience', models.CharField(choices=[('all', 'Everyone'), ('student', 'Students'), ('parent', 'Parents'), ('teacher', 'Teachers')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_method', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('physical', 'Physical')], max_length=20)),
                ('details', models.TextField(help_text='Details: email sent to, WhatsApp timestamp, physical date, etc.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=20)),
                ('teacher_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Assignment Ticket',
                'verbose_name_plural': 'Assignment Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('half_day', 'Half Day')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BrushUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('brushup', 'Brush-Up Session'), ('retest', 'Re-test Request')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('teacher_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brush-Up Request',
                'verbose_name_plural': 'Brush-Up Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('student', 'Student Comment'), ('teacher', 'Teacher Comment'), ('parent', 'Parent Comment'), ('general', 'General Comment'), ('progress', 'Progress Note'), ('behavior', 'Behavior Note')], default='general', max_length=20)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Visible to admins only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('suggestion', 'Suggestion'), ('complaint', 'Complaint'), ('appreciation', 'Appreciation'), ('query', 'Query')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='End date for multi-day events', null=True)),
                ('description', models.TextField(blank=True)),
                ('holiday_type', models.CharField(choices=[('holiday', 'Holiday'), ('working_day', 'Special Working Day'), ('half_day', 'Half Day'), ('exam', 'Exam Day')], default='holiday', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('assignment', 'New Assignment'), ('grade', 'Grade Posted'), ('comment', 'New Comment'), ('holiday', 'Holiday Announcement'), ('attendance', 'Attendance Alert'), ('general', 'General Notification'), ('ticket', 'Ticket Update'), ('brushup', 'Brush-Up Update')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('target_role', models.CharField(choices=[('all', 'Everyone'), ('student', 'Students'), ('parent', 'Parents'), ('teacher', 'Teachers')], default='all', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Status Post',
                'verbose_name_plural': 'Status Posts',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='roadmaptopic',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Roadmap Topic', 'verbose_name_plural': 'Roadmap Topics'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['grade', 'section', 'roll_number'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='testscore',
            options={'ordering': ['-date'], 'verbose_name': 'Test Score', 'verbose_name_plural': 'Test Scores'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RenameField(
            model_name='roadmaptopic',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='testscore',
            old_name='test_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='roadmaptopic',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='roadmaptopic',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='roadmaptopic',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='testscore',
            name='scored_marks',
        ),
        migrations.RemoveField(
            model_name='testscore',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='testscore',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, help_text='Assignment file (PDF, DOC, DOCX — max 10MB)', null=True, upload_to='assignments/', validators=[core.models.validate_file_extension, core.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='estimated_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='parent_topic',
            field=models.ForeignKey(blank=True, help_text='Parent topic for hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='core.roadmaptopic'),
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='resources',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='test_duration',
            field=models.IntegerField(blank=True, help_text='Test duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='test_scheduled',
            field=models.DateField(blank=True, help_text='Scheduled test date', null=True),
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='test_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='roadmaptopic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_method',
            field=models.CharField(choices=[('online', 'Online Upload'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('physical', 'Physical Submission')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testscore',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testscore',
            name='grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='testscore',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='testscore',
            name='roadmap_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_scores', to='core.roadmaptopic'),
        ),
        migrations.AddField(
            model_name='testscore',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='testscore',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Residential address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile picture (JPG, PNG, GIF)', null=True, upload_to='profile_photos/', validators=[core.models.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(help_text='Detailed assignment instructions'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(help_text='Submission deadline'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='roadmaptopic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='roadmaptopic',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(help_text='Current grade/class', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent/Guardian', limit_choices_to={'profile__role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(help_text='Section (A, B, C, etc.)', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, help_text='Submission file (PDF, DOC, DOCX)', null=True, upload_to='submissions/', validators=[core.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('graded', 'Graded'), ('resubmit', 'Needs Resubmission'), ('late', 'Late Submission')], default='not_submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_set', to='core.student'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=20),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['-created_at'], name='core_assign_created_18316c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='core_assign_due_dat_5b7b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status'], name='core_assign_status_7d23cd_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmaptopic',
            index=models.Index(fields=['order'], name='core_roadma_order_f2f9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmaptopic',
            index=models.Index(fields=['status'], name='core_roadma_status_37ebca_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmaptopic',
            index=models.Index(fields=['created_by'], name='core_roadma_created_8129e4_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['grade', 'section'], name='core_studen_grade_08f7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['roll_number'], name='core_studen_roll_nu_9cbe47_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='core_submis_status_74b714_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-submitted_at'], name='core_submis_submitt_447f4e_idx'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentticket',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentticket',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentticket',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_set', to='core.student'),
        ),
        migrations.AddField(
            model_name='brushuprequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brushup_requests', to='core.student'),
        ),
        migrations.AddField(
            model_name='brushuprequest',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brushup_requests', to='core.roadmaptopic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_holidays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statuspost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'),
        ),
    ]
