# Generated by Django 5.0.1 on 2026-02-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_announcement_assignmentticket_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject name e.g. Mathematics, Science, ICT', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher responsible for this subject', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectsTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(help_text='Student enrolled in this subject', on_delete=django.db.models.deletion.CASCADE, related_name='subjects_taken', to='core.student')),
                ('subject', models.ForeignKey(help_text='Subject the student is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='core.subject')),
            ],
            options={
                'verbose_name': 'Subject Taken',
                'verbose_name_plural': 'Subjects Taken',
                'ordering': ['student', 'subject__name'],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
