# Generated by Django 5.0.1 on 2026-02-20 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subject_subjectstaken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly salary e.g. 12000.00', max_digits=10)),
                ('joining_date', models.DateField(blank=True, help_text='Date teacher joined the school', null=True)),
                ('qualification', models.CharField(blank=True, choices=[('b_ed', 'B.Ed'), ('m_ed', 'M.Ed'), ('b_sc', 'B.Sc'), ('m_sc', 'M.Sc'), ('b_a', 'B.A'), ('m_a', 'M.A'), ('phd', 'Ph.D'), ('other', 'Other')], help_text='Highest academic qualification', max_length=10)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact phone number', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(help_text='UserProfile of the teacher (role must be teacher)', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
                'ordering': ['profile__user__first_name', 'profile__user__last_name'],
            },
        ),
    ]
