# Generated by Django 5.0.1 on 2026-02-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='Not provided', help_text='Student residential address e.g. Viman Nagar, Pune'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='0000000000', help_text='Student contact phone number e.g. 9187263541', max_length=15),
            preserve_default=False,
        ),
    ]
