# Generated by Django 5.0.1 on 2026-02-20 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_address_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Running total of unpaid/overdue fees (auto-updated)', max_digits=10),
        ),
        migrations.CreateModel(
            name='FeesStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Month and year in MM/YYYY format e.g. 01/2026', max_length=7)),
                ('fees', models.DecimalField(decimal_places=2, help_text='Fee amount set by Admin e.g. 10000.00', max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='unpaid', help_text='Payment status', max_length=10)),
                ('due_date', models.DateField(help_text='Date by which payment is due')),
                ('paid_date', models.DateField(blank=True, help_text='Date payment was received — leave blank if not yet paid', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Optional notes e.g. partial payment, scholarship etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student this fee record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.student')),
            ],
            options={
                'verbose_name': 'Fee Status',
                'verbose_name_plural': 'Fee Status Records',
                'ordering': ['-month', 'student'],
                'unique_together': {('student', 'month')},
            },
        ),
    ]
